name: CodersCamp2020 | ⚽️ Table Soccer Tournaments UI - React

on:
  push:
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**'
      - '!**/README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CI: true

    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - uses: actions/upload-artifact@v1
        name: Upload build as artifact
        with:
          name: tournament-build
          path: ./frontend/build

  deploy-on-github-pages:
    name: 'Deploy app to GitHub Pages from develop branch source code'
    if: github.ref == 'refs/heads/develop'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: tournament-build
          path: ./frontend/build
      - name: Deploy app as GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.0-6
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './frontend/build'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
          keep_files: false
